services:
  syncryn1z3-ptp:
    build: .
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    # Define the port mapping (external:internal port)
    ports:
      - 319:319/udp
      - 320:320/udp

    restart: unless-stopped

    mem_limit: 500m
    cpus: 1

  syncryn1z3-web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 1588:8000
    depends_on:
      - syncryn1z3-ptp

    restart: unless-stopped

    mem_limit: 500m
    cpus: 0.1
