version: "3.8"

services:
  app:
    build:
      context: .
    container_name: go-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://user:password@db:5432/db_name
    volumes:
      - .:/app
    depends_on:
      - oracle-db

  oracle-db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
